Update vagrant test

diff --git a/tests/vagrant-test b/tests/vagrant-test
--- a/tests/vagrant-test
+++ b/tests/vagrant-test
@@ -1,11 +1,27 @@
 #!/usr/bin/env bash
 set -e
 
+# Check if vagrant is installed.
 if ! [ -x "$(command -v vagrant)" ]; then
   echo 'Error: vagrant is not installed.' >&2
   exit 1
 fi
 
+# Check if the test run before.
+if [ -e "andock-vagrant-test" ]; then
+    echo "Folder andock-vagrant-test already exists. Run vagrant destroy and rm -r andock-vagrant-test"
+    exit 1
+fi
+# Ask for ssh key
+read -e -p "Which SSH key should be used?: [~/.ssh/id_rsa.pub]" KEY
+if [ "$KEY" = "" ]; then
+    KEY="~/.ssh/id_rsa.pub"
+fi
+eval KEY=$KEY
+if [ ! -e "$KEY" ]; then
+    echo "SSH key not found"
+    exit 1
+fi
 
 mkdir andock-vagrant-test
 cd andock-vagrant-test
@@ -13,9 +29,6 @@ cd andock-vagrant-test
 # Download vagrant file.
 curl --output Vagrantfile https://raw.githubusercontent.com/andock/andock/master/tests/vagrant/Vagrantfile
 
-# Ask for ssh key
-read -e -p "Which SSH key should be used?: " -i "~/.ssh/id_rsa.pub" KEY
-eval KEY=$KEY
 sed -i -e "s,id_rsa.pub,$KEY,g" "Vagrantfile"
 
 # Start vagrant
@@ -29,7 +42,7 @@ echo "192.168.33.10    andock.local"
 echo "192.168.33.10    master.demo-project.andock.local"
 echo
 echo ""
-echo "You should now connect to the vagrant box with ssh root@dev.andock.local"
+echo "You should now connect to the vagrant box with ssh root@andock.local"
 echo ""
 echo "Go to now demo-project and follow the 5 minutes guide"
 echo
